### ISSUE TITLE
Include ftplugin

### ISSUE THREAD

**Issue by romainl** [wuelnerdotexe/vim-astro#2]
Hello, and thank you for this plugin.

Do you intend this repo to stay focused on indenting and syntax highlighting only or would you be open to also include an extensive ftplugin?

I have been experimenting with Astro at work, which of course involved a bit of tweaking in Vim, and I came up with a pretty clean ftplugin (+ supporting autoloaded functions) that seems to do a good job so far. The content of the ftplugin is a mix of settings pulled from related built-in ftplugins (JavaScript, TypeScript, HTML, CSS, SASS) and Astro-specific settings.

Note: I only use Vim so it is untested in Neovim.

**Comment by wuelnerdotexe** [comment]
Hello! @romainl - Of course, an `ftplugin` would be welcome if the setup is only native to Vim/Neovim (no external plugins), and if you think the setup might make sense for everyone. If so...

You can send your PR !! or if you prefer you can attach the code in this issue you can also do it. 😀

**Comment by romainl** [comment]
The PR is over there: https://github.com/wuelnerdotexe/vim-astro/pull/3.
