### ISSUE TITLE
Not working with Lazy nvim

### ISSUE THREAD

**Issue by anoopd** [wuelnerdotexe/vim-astro#5]
I tried to install this with lazy.nvim 

```
   return {
	  {
		"wuelnerdotexe/vim-astro",
	  },
    }
```
It gets installed but syntax is not being highlighted . Should i `require`  this in my init.lua

**Comment by AodhanOlan** [comment]
Any solutions? Faced the same problem(

**Comment by wuelnerdotexe** [comment]
Hi! @anoopd, @AodhanOlan - sorry for the late reply, with `lazy.nvim` everything works as it should with the following setup:
```lua
return {
  {
    "wuelnerdotexe/vim-astro",
    ft = "astro",
    init = function()
      -- Astro configuration variables.
      vim.g.astro_typescript = "enable"
      vim.g.astro_stylus     = "disable"
    end,
  },
}
```
Could you try and close this issue only if it works for you? Thank you :)
